In [ ]:
**MI CURRICULUM VITAE**

*Luis Guillermo Vargas Aparicio*

## Me encuentras en tweeter así:@LuisGui17167201

# Vengo de la ciudad amurallada,del sector Getsemani

##Toda mi niñez fue alredor del mar,y mis estudios los realice dentro del corralito de piedra,esto me permitio aprenderme todos los nombres de las calles de mi hermosa cíudad al ir cambiando las rutas para llegar al destino elegido,ya fuese,la casa o el colegio##

### Estudie en la Universidad de Cartagena,de la cual me gradue de Ingeniero Civil,aunque simultaneamente estudiaba Ingenieria Electrica en la Universidad Tecnológica de Bolivar###

#### Después estudie en otras universidades cono la Universidad Industrial de Santander-UIS,La Univarsidad Javeriana y otras.

He participado en la construcción de más de 20 Plantas Industriales y de las cuales hemos aportado en el arranque de unas cinco.

**ASPIRO SER UN CIENTIFICO DE DATOS CERTIFICADO PARA BRINDAR CONOCIMIENTO A NUESTRO PAIS Y PLANETA YA QUE ME CONSIDERO UN CIUDADANO DEL MUNDO**


In [10]:
# Librería para leer Código HTML y ejecutarlo
from IPython.display import HTML
# Código HTML
html1 = '<img src="../OneDrive/Imágenes/Foto de Luis para Diplomado.jpg" width="255000" height="222600" align="center"/>'
# Ejecutar instrucción a través de Python
HTML(html1)

In [1]:
import numpy as np

In [2]:
a=np.array(13) #array de dimensión 0
b=np.array([1,2,3,4]) #array de dimensión 1
c=np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3

print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")

a = 13 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



In [3]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
np.add(arr1,arr2)

array([[7, 7, 7],
       [7, 7, 7]])

In [5]:
a= np.array([1,2,3,4,5,8])
print(a)

[1 2 3 4 5 8]


In [6]:
newarray=np.append(a,[12,15,18,20])
print(newarray)

[ 1  2  3  4  5  8 12 15 18 20]


In [7]:
import pandas as pd

In [8]:
#from google.colab import ##drive correr solo en colab
#drive.mount('/content/gdrive')
counties = pd.read_excel("https://github.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/blob/main/Python/Datos/counties.xlsx?raw=true")#cambiar dirección

In [9]:
counties

codestate  codecounty                 county  population         area
0             1        1001          Auta#%&()uga      54571.0   594.436000
1             1        1003   Baldwin#%&()  ?         182265.0  1589.784000
2             1        1005               Barbour      27457.0   884.876000
3             1        1007             Bi#%&()bb      22915.0   622.582000
4             1        1009         Blount  ?          57322.0   644.776000
...         ...         ...                    ...         ...          ...
3229         72       72151               Yabucoa      37941.0    55.215000
3230         72       72153                Ya_uco      42043.0    68.192000
3231         78       78010     ; St. Croix ?          50601.0    83.345868
3232         78       78020               St. John      4170.0    19.689867
3233         78       78030             St. Thomas     51634.0    31.313503

[3234 rows x 5 columns]

In [10]:
counties.head(9)

codestate  codecounty                 county  population      area
0          1        1001          Auta#%&()uga      54571.0   594.436
1          1        1003   Baldwin#%&()  ?         182265.0  1589.784
2          1        1005               Barbour      27457.0   884.876
3          1        1007             Bi#%&()bb      22915.0   622.582
4          1        1009         Blount  ?          57322.0   644.776
5          1        1011          Bull#%&()ock      10914.0   622.805
6          1        1013              ; Butler      20947.0   776.829
7          1        1015               Calhoun     118572.0   605.868
8          1        1017     ; Chambers  ?          34215.0   596.531

In [11]:
counties.tail(4)

codestate  codecounty                 county  population       area
3230         72       72153                Ya_uco      42043.0  68.192000
3231         78       78010     ; St. Croix ?          50601.0  83.345868
3232         78       78020               St. John      4170.0  19.689867
3233         78       78030             St. Thomas     51634.0  31.313503

In [12]:
display(counties)

codestate  codecounty                 county  population         area
0             1        1001          Auta#%&()uga      54571.0   594.436000
1             1        1003   Baldwin#%&()  ?         182265.0  1589.784000
2             1        1005               Barbour      27457.0   884.876000
3             1        1007             Bi#%&()bb      22915.0   622.582000
4             1        1009         Blount  ?          57322.0   644.776000
...         ...         ...                    ...         ...          ...
3229         72       72151               Yabucoa      37941.0    55.215000
3230         72       72153                Ya_uco      42043.0    68.192000
3231         78       78010     ; St. Croix ?          50601.0    83.345868
3232         78       78020               St. John      4170.0    19.689867
3233         78       78030             St. Thomas     51634.0    31.313503

[3234 rows x 5 columns]

In [14]:
counties.info()
print("\n")
print("La forma de la base de datos es:",counties.shape)  #shape:forma de un array


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3234 entries, 0 to 3233
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   codestate   3234 non-null   int64  
 1   codecounty  3234 non-null   int64  
 2   county      3234 non-null   object 
 3   population  3232 non-null   float64
 4   area        3234 non-null   float64
dtypes: float64(2), int64(2), object(1)
memory usage: 126.5+ KB


La forma de la base de datos es: (3234, 5)


In [15]:
print(counties.dtypes) #tipo de objeto en cada columna
print("\n")
print(counties.describe())
print("\n")
print(counties.describe(include="all")) #summary, si no se pone el include solo aparece de las variables numéricas

codestate       int64
codecounty      int64
county         object
population    float64
area          float64
dtype: object


         codestate    codecounty    population           area
count  3234.000000   3234.000000  3.232000e+03    3234.000000
mean     31.441868  31544.737786  9.679656e+04    1093.361817
std      16.411236  16425.545223  3.088044e+05    3564.706999
min       1.000000   1001.000000  1.700000e+01       0.031696
25%      19.000000  19039.500000  1.129700e+04     416.360000
50%      30.000000  30038.000000  2.607550e+04     602.977500
75%      46.000000  46128.500000  6.566050e+04     913.884500
max      78.000000  78030.000000  9.818605e+06  145504.789000


          codestate    codecounty    county    population           area
count   3234.000000   3234.000000      3234  3.232000e+03    3234.000000
unique          NaN           NaN      2625           NaN            NaN
top             NaN           NaN  Lincoln            NaN            NaN
freq            NaN   

In [16]:
counties.columns

Index(['codestate', 'codecounty', 'county', 'population', 'area'], dtype='object')

In [17]:
condado = counties["county"]
condado

0               Auta#%&()uga 
1        Baldwin#%&()  ?     
2                    Barbour 
3                  Bi#%&()bb 
4              Blount  ?     
                ...          
3229                 Yabucoa 
3230                  Ya_uco 
3231       ; St. Croix ?     
3232                 St. John
3233               St. Thomas
Name: county, Length: 3234, dtype: object

In [18]:
print(condado.shape) #array unidimensional con 3234 elementos
print(counties["county"].shape)
print(type(condado))

(3234,)
(3234,)
<class 'pandas.core.series.Series'>


In [19]:
codi_condado=counties[["codecounty","county"]]
print(codi_condado)
print(type(codi_condado))

      codecounty                 county
0           1001          Auta#%&()uga 
1           1003   Baldwin#%&()  ?     
2           1005               Barbour 
3           1007             Bi#%&()bb 
4           1009         Blount  ?     
...          ...                    ...
3229       72151               Yabucoa 
3230       72153                Ya_uco 
3231       78010     ; St. Croix ?     
3232       78020               St. John
3233       78030             St. Thomas

[3234 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>


In [20]:
from seaborn import load_dataset

In [21]:
print(counties.iloc[0:1,])
print(type(counties.iloc[0:1,]))

   codestate  codecounty         county  population     area
0          1        1001  Auta#%&()uga      54571.0  594.436
<class 'pandas.core.frame.DataFrame'>


In [22]:
print(counties.iloc[8:12,1:3])

    codecounty                 county
8         1017     ; Chambers  ?     
9         1019              Cherokee 
10        1021             ; Chilton 
11        1023               Choctaw 


In [23]:
print(counties.iloc[8:14,1:5])

    codecounty                  county  population      area
8         1017      ; Chambers  ?          34215.0   596.531
9         1019               Cherokee      25989.0   553.700
10        1021              ; Chilton      43643.0   692.854
11        1023                Choctaw      13859.0   913.500
12        1025                 Clarke      25833.0  1238.465
13        1027     ; Cla#%&()y  ?          13932.0   603.961


In [24]:
counties.tail()

codestate  codecounty                 county  population       area
3229         72       72151               Yabucoa      37941.0  55.215000
3230         72       72153                Ya_uco      42043.0  68.192000
3231         78       78010     ; St. Croix ?          50601.0  83.345868
3232         78       78020               St. John      4170.0  19.689867
3233         78       78030             St. Thomas     51634.0  31.313503

In [25]:
counties.tail(18)

codestate  codecounty                      county  population  \
3216         72       72125                 San Germán      35527.0   
3217         72       72127                   San Juan     395326.0   
3218         72       72129               Sa_n Lorenzo      41058.0   
3219         72       72131  San Sebast#%&()ián  ?          42430.0   
3220         72       72133               Santa Isabel      23274.0   
3221         72       72135            Toa_ #%&()Alta_      74066.0   
3222         72       72137              Toa #%&()Baja      89609.0   
3223         72       72139              Trujillo Alto      74842.0   
3224         72       72141             Utua_do  ?          33149.0   
3225         72       72143           Vega_ #%&()Alta_      39951.0   
3226         72       72145             Vega #%&()Baja      59662.0   
3227         72       72147           ; Vieques  ?           9301.0   
3228         72       72149               ; Villa_lba_      26073.0   
3229         72       72151                    Yabucoa      37941.0   
3230         72       72153                     Ya_uco      42043.0   
3231         78       78010          ; St. Croix ?          50601.0   
3232         78       78020                    St. John      4170.0   
3233         78       78030                  St. Thomas     51634.0   

            area  
3216   54.498000  
3217   47.847000  
3218   53.108000  
3219   70.423000  
3220   34.023000  
3221   27.016000  
3222   23.241000  
3223   20.764000  
3224  113.529000  
3225   27.728000  
3226   45.856000  
3227   50.768000  
3228   35.637000  
3229   55.215000  
3230   68.192000  
3231   83.345868  
3232   19.689867  
3233   31.313503

In [26]:
counties["codestate"] > 36 #Verdadero o falso si cumple la condición

0       False
1       False
2       False
3       False
4       False
        ...  
3229     True
3230     True
3231     True
3232     True
3233     True
Name: codestate, Length: 3234, dtype: bool

In [27]:
codsat36 = counties[counties["codestate"] > 36] # Llama aquellos cuyo valor es verdadero
codsat36.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1344 entries, 1890 to 3233
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   codestate   1344 non-null   int64  
 1   codecounty  1344 non-null   int64  
 2   county      1344 non-null   object 
 3   population  1342 non-null   float64
 4   area        1344 non-null   float64
dtypes: float64(2), int64(2), object(1)
memory usage: 63.0+ KB


In [28]:
no_na = counties[counties["population"].notna()]

print(no_na.shape)
print(counties.shape)

(3232, 5)
(3234, 5)


In [29]:
codcou1 = counties[counties["codecounty"].isin([78010, 72151])]
codcou1

codestate  codecounty                 county  population       area
3229         72       72151               Yabucoa      37941.0  55.215000
3231         78       78010     ; St. Croix ?          50601.0  83.345868

In [30]:
codcou2 = counties.loc[:, 'codecounty'] == 78010
codcou2_ = counties.loc[codcou2]
codcou2_

codestate  codecounty                 county  population       area
3231         78       78010     ; St. Croix ?          50601.0  83.345868

In [31]:
counties[(counties["codecounty"] == 78010) | (counties["codecounty"] == 72151)]

codestate  codecounty                 county  population       area
3229         72       72151               Yabucoa      37941.0  55.215000
3231         78       78010     ; St. Croix ?          50601.0  83.345868

In [32]:
counties[(counties["codestate"] == 36) & (counties["area"] >= 60)].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59 entries, 1828 to 1889
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   codestate   59 non-null     int64  
 1   codecounty  59 non-null     int64  
 2   county      59 non-null     object 
 3   population  59 non-null     float64
 4   area        59 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.8+ KB


In [33]:
#Eliminar valores omitidos: dropna
# axis= 0 -> Eliminar fila completa
# axis=1 -> Eliminar columna completa
counties.dropna(subset=["population"], axis=0, inplace=False) #inplace:modifique directamente la BD

codestate  codecounty                 county  population         area
0             1        1001          Auta#%&()uga      54571.0   594.436000
1             1        1003   Baldwin#%&()  ?         182265.0  1589.784000
2             1        1005               Barbour      27457.0   884.876000
3             1        1007             Bi#%&()bb      22915.0   622.582000
4             1        1009         Blount  ?          57322.0   644.776000
...         ...         ...                    ...         ...          ...
3229         72       72151               Yabucoa      37941.0    55.215000
3230         72       72153                Ya_uco      42043.0    68.192000
3231         78       78010     ; St. Croix ?          50601.0    83.345868
3232         78       78020               St. John      4170.0    19.689867
3233         78       78030             St. Thomas     51634.0    31.313503

[3232 rows x 5 columns]

In [36]:
counties["county"] = (counties["county"]
                            .str.lower()
                            .str.replace("[^a-záéíóúüñ ]","")
                            .str.replace(" +"," ")
                            .str.strip()
                            .str.title()
                        

SyntaxError: unexpected EOF while parsing (621507366.py, line 7)

In [37]:
print(counties.shape)
counties = counties.drop(counties.iloc[0:3,].index)
counties = counties.drop(counties[counties['codecounty']==70].index)
print(counties.shape)

(3234, 5)
(3231, 5)


In [39]:
group=counties.groupby("codestate")
print(type(group))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [40]:
print(group.first().head(10)) # Nos muestra el primer elemento de cada grupo según "codestate"
print('\n')
print(group.get_group(78)) #Nos muestra los elementos cuyo codestate es 78

           codecounty                county  population       area
codestate                                                         
1                1007            Bi#%&()bb      22915.0    622.582
2                2013       Aleutians East       3141.0   6981.943
4                4001        Apache  ?          71518.0  11197.521
5                5001        Arka#%&()nsas      19019.0    988.770
6                6001              Alameda    1510271.0    739.017
8                8001                Adams     441603.0   1167.653
9                9001          ; Fairfield     916829.0    624.890
10              10001                 Kent     162310.0    586.179
11              11001  District of Columbia    601723.0     61.048
12              12001            Ala_chua_     247336.0    875.020


      codestate  codecounty                 county  population       area
3231         78       78010     ; St. Croix ?          50601.0  83.345868
3232         78       78020               St. 

In [41]:
counties.groupby("codestate")["codecounty"].count().head(20)

codestate
1      64
2      29
4      15
5      75
6      58
8      64
9       8
10      3
11      1
12     67
13    159
15      5
16     44
17    102
18     92
19     99
20    105
21    120
22     64
23     16
Name: codecounty, dtype: int64

In [42]:
folder_path="https://github.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/blob/main/Python/Datos/"

In [45]:
elections=pd.read_excel(folder_path+'elections.xlsx?raw=true')
elections.head(5)

year  democrat  republic  other  codecounty
0  2000      4942     11993    273        1001
1  2000     13997     40872   1611        1003
2  2000      5188      5096    111        1005
3  2000      2710      4273    118        1007
4  2000      4977     12667    329        1009

In [46]:
elections.sort_values(["democrat"], ascending=False)

year  democrat  republic   other  codecounty
12626  2016   2464364    769743  200201        6037
6400   2008   2295853    956425   65970        6037
9513   2012   2216903    885333   78831        6037
3287   2004   1907736   1076225   37686        6037
175    2000   1710505    871930  112719        6037
...     ...       ...       ...     ...         ...
11981  2012         9        54       1       48301
8852   2008         8       151       4       48269
11965  2012         5       139       1       48269
15078  2016         5       149       5       48269
15094  2016         4        58       3       48301

[15563 rows x 5 columns]

In [47]:
elections.groupby('year')[['democrat', 'republic']].sum()

democrat  republic
year                    
2000  50922964  50290498
2004  58614073  61603653
2008  69204582  59703000
2012  65508961  60460609
2016  65626398  62790289

In [48]:
elections_sort=(elections.groupby('year')[['democrat', 'republic']]
                .sum()
                .sort_values('democrat', ascending=False))
display(elections_sort)

democrat  republic
year                    
2008  69204582  59703000
2016  65626398  62790289
2012  65508961  60460609
2004  58614073  61603653
2000  50922964  50290498

In [49]:
pivot_elections=elections.pivot(index='codecounty',
                columns='year',
                values=['democrat','republic'])
pivot_elections.head()


democrat                                     republic           \
year           2000     2004     2008     2012     2016     2000     2004   
codecounty                                                                  
1001         4942.0   4758.0   6093.0   6363.0   5936.0  11993.0  15196.0   
1003        13997.0  15599.0  19386.0  18424.0  18458.0  40872.0  52971.0   
1005         5188.0   4832.0   5697.0   5912.0   4871.0   5096.0   5899.0   
1007         2710.0   2089.0   2299.0   2202.0   1874.0   4273.0   5472.0   
1009         4977.0   3938.0   3522.0   2970.0   2156.0  12667.0  17386.0   

                                       
year           2008     2012     2016  
codecounty                             
1001        17403.0  17379.0  18172.0  
1003        61271.0  66016.0  72883.0  
1005         5866.0   5550.0   5454.0  
1007         6262.0   6132.0   6738.0  
1009        20389.0  20757.0  22859.0

In [51]:
counties_multi=pd.read_excel(folder_path+"counties.xlsx?raw=true", index_col=[0, 1])
display(counties_multi)

county  population         area
codestate codecounty                                                
1         1001                Auta#%&()uga      54571.0   594.436000
          1003         Baldwin#%&()  ?         182265.0  1589.784000
          1005                     Barbour      27457.0   884.876000
          1007                   Bi#%&()bb      22915.0   622.582000
          1009               Blount  ?          57322.0   644.776000
...                                     ...         ...          ...
72        72151                    Yabucoa      37941.0    55.215000
          72153                     Ya_uco      42043.0    68.192000
78        78010          ; St. Croix ?          50601.0    83.345868
          78020                    St. John      4170.0    19.689867
          78030                  St. Thomas     51634.0    31.313503

[3234 rows x 3 columns]

In [52]:
counties_multi['population'].sum(level='codestate').head(8)

C:\Users\redpe\AppData\Local\Temp\ipykernel_15736\322084879.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  counties_multi['population'].sum(level='codestate').head(8)


codestate
1      4779736.0
2       710231.0
4      6392017.0
5      2915918.0
6     37253956.0
8      5029196.0
9      3574097.0
10      897934.0
Name: population, dtype: float64

In [53]:
elections_2000=elections[elections['year']==2000]
display(elections_2000) #display:ejecuta el método dunder apropiado para obtener los datos apropiados para mostrar

year  democrat  republic  other  codecounty
0     2000      4942     11993    273        1001
1     2000     13997     40872   1611        1003
2     2000      5188      5096    111        1005
3     2000      2710      4273    118        1007
4     2000      4977     12667    329        1009
...    ...       ...       ...    ...         ...
3107  2000      5521      9425    745       56037
3108  2000      4019      5454    958       56039
3109  2000      1650      5469    299       56041
3110  2000       806      3138    107       56043
3111  2000       449      2521     90       56045

[3112 rows x 5 columns]

In [54]:
elections_2004=elections[elections['year']==2004]
elections_2004['dummy']=0
display(elections_2004)

C:\Users\redpe\AppData\Local\Temp\ipykernel_15736\3665125724.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elections_2004['dummy']=0


year  democrat  republic  other  codecounty  dummy
3112  2004      4758     15196    127        1001      0
3113  2004     15599     52971    750        1003      0
3114  2004      4832      5899     46        1005      0
3115  2004      2089      5472     39        1007      0
3116  2004      3938     17386    180        1009      0
...    ...       ...       ...    ...         ...    ...
6220  2004      5208     10653    411       56037      0
6221  2004      5972      5124    263       56039      0
6222  2004      1815      6081    185       56041      0
6223  2004       855      3200     59       56043      0
6224  2004       580      2739     73       56045      0

[3113 rows x 6 columns]

In [55]:
elections_00_04=pd.concat([elections_2000, elections_2004])
display(elections_00_04)

year  democrat  republic  other  codecounty  dummy
0     2000      4942     11993    273        1001    NaN
1     2000     13997     40872   1611        1003    NaN
2     2000      5188      5096    111        1005    NaN
3     2000      2710      4273    118        1007    NaN
4     2000      4977     12667    329        1009    NaN
...    ...       ...       ...    ...         ...    ...
6220  2004      5208     10653    411       56037    0.0
6221  2004      5972      5124    263       56039    0.0
6222  2004      1815      6081    185       56041    0.0
6223  2004       855      3200     59       56043    0.0
6224  2004       580      2739     73       56045    0.0

[6225 rows x 6 columns]

In [56]:
display(counties)

codestate  codecounty                 county  population        area
3             1        1007             Bi#%&()bb      22915.0  622.582000
4             1        1009         Blount  ?          57322.0  644.776000
5             1        1011          Bull#%&()ock      10914.0  622.805000
6             1        1013              ; Butler      20947.0  776.829000
7             1        1015               Calhoun     118572.0  605.868000
...         ...         ...                    ...         ...         ...
3229         72       72151               Yabucoa      37941.0   55.215000
3230         72       72153                Ya_uco      42043.0   68.192000
3231         78       78010     ; St. Croix ?          50601.0   83.345868
3232         78       78020               St. John      4170.0   19.689867
3233         78       78030             St. Thomas     51634.0   31.313503

[3231 rows x 5 columns]

In [57]:
inner_joined=pd.merge(elections, counties)
inner_joined.head(12)

year  democrat  republic  other  codecounty  codestate          county  \
0   2000      2710      4273    118        1007          1      Bi#%&()bb    
1   2004      2089      5472     39        1007          1      Bi#%&()bb    
2   2008      2299      6262     83        1007          1      Bi#%&()bb    
3   2012      2202      6132     86        1007          1      Bi#%&()bb    
4   2016      1874      6738    207        1007          1      Bi#%&()bb    
5   2000      4977     12667    329        1009          1  Blount  ?        
6   2004      3938     17386    180        1009          1  Blount  ?        
7   2008      3522     20389    356        1009          1  Blount  ?        
8   2012      2970     20757    279        1009          1  Blount  ?        
9   2016      2156     22859    573        1009          1  Blount  ?        
10  2000      3395      1433     76        1011          1   Bull#%&()ock    
11  2004      3210      1494     13        1011          1   Bull#%&()ock    

    population     area  
0      22915.0  622.582  
1      22915.0  622.582  
2      22915.0  622.582  
3      22915.0  622.582  
4      22915.0  622.582  
5      57322.0  644.776  
6      57322.0  644.776  
7      57322.0  644.776  
8      57322.0  644.776  
9      57322.0  644.776  
10     10914.0  622.805  
11     10914.0  622.805

In [58]:
m=np.random.rand(12)

In [59]:
print(m)

[0.43999663 0.83243362 0.67569847 0.38686437 0.75016737 0.25802804
 0.90237997 0.09744768 0.37985454 0.80950432 0.73615819 0.47075765]


In [60]:
m=np.random.randint(12)
print(m)

0


In [61]:
m=np.random.randint(1,30,size =15)
print(m)

[ 3 23 28 10  4 12  2 16  9 15  6 28 15  4 19]


In [63]:
m=np.random.rand(2,2)
print(m)

[[0.31899303 0.00598648]
 [0.13813337 0.34146451]]


In [64]:
m=np.random.rand(3,2)
print(m)

[[0.20507848 0.05838203]
 [0.52600666 0.31674845]
 [0.65225195 0.2804565 ]]


In [66]:
m=np.random.rand(7,7)
print(m)

[[0.02009069 0.42352049 0.50681805 0.43485322 0.94592597 0.1356663
  0.98931308]
 [0.07792201 0.30450494 0.53266161 0.33771761 0.16335592 0.75266558
  0.43704336]
 [0.88440899 0.72559851 0.80951495 0.03741479 0.7438517  0.46521173
  0.78946005]
 [0.93258766 0.06828066 0.75793222 0.21505612 0.40479311 0.46169642
  0.30950246]
 [0.34622631 0.680473   0.85572601 0.81929409 0.76329113 0.25196446
  0.72506778]
 [0.31509392 0.7253376  0.59341927 0.78577777 0.76283003 0.56782816
  0.10549338]
 [0.29228898 0.33606297 0.45522227 0.83507223 0.12401033 0.02782829
  0.40659812]]
